routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::resource('artwork', 'ArtworkController');
Route::resource('user', 'UserController');

Route::get('fresh', 'ArtworkController@fresh')->name('artwork.fresh');
Route::get('trends', 'ArtworkController@trends')->name('artwork.trends');

Route::get('home', 'HomeController@index')->name('home');
Route::get('search', 'SearchController@search')->name('artwork.search');

app/Artwork.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Nicolaslopezj\Searchable\SearchableTrait;
class Artwork extends Model
{
    use SearchableTrait;
    
    public $timestamps = false;
    protected $searchable = [
        'columns' => [
            'artworks.name' => 10,
            'artworks.description' => 5,
            'users.name'=>5,
        ],
        'joins' => [
            'users' => ['users.id','artworks.user_id'],
        ],
        
    ];
    public function comments()
    {
        return $this->hasMany('App\Comment');
    }
    public function artwork_categories()
    {
        return $this->hasMany('App\ArtworkCategory');
    }
    public function artwork_tags()
    {
        return $this->hasMany('App\ArtworkTag');
    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }
   }

app/Http/Controllers/ArtworkController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use App\Artwork;
use App\ArtworkCategory;
use App\ArtworkTag;
use App\Tag;
use Carbon\Carbon;
class ArtworkController extends Controller
{



    public function __construct()
    {
        $this->middleware('auth', ['only' => ['create', 'store', 'delete','edit','update']]);
    }

    public function index()
    {
        return view('artwork.index', ['artworks' => Artwork::paginate(12)]);
    }
    
    public function create()
    {
        $categories=\App\Category::all();
        return view('artwork.create')->with('categories', $categories);
    }
    public function store(Request $request)
    {
        $this->validate($request,[
            'title'=>'required|max:30',
            'description'=>'max:2000',
            'category'=>'required',
            'artwork' => 'required|file|mimes:jpeg,bmp,png|max:10000',
        ]);
        $artwork=new Artwork;
        $artwork_categories=new ArtworkCategory;

        $artwork->name=$request->title;
        $artwork->description=$request->description;
        $path=$request->file('artwork')->store('public/artworks');
        $artwork->file_path=basename($path);
        $artwork->user_id=\Auth::user()->id;
       
        
        $artwork->save();

        $artwork_categories->artwork_id=$artwork->id;
        $artwork_categories->category_id=$request->category;
        $artwork_categories->save();

        $words = preg_split('/\s+/', $request->tags, -1, PREG_SPLIT_NO_EMPTY);

        foreach($words as $rawTag){
        $tag = Tag::where('name', $rawTag)->first();
                        if ($tag==null ){
                            $tag=Tag::create([
                                'name' => $rawTag,
                                'count'=>1,
                            ]);
                        }
                        else{
                            $tag->count++;
                            $tag->save();
                        }
                        ArtworkTag::create([
                            'artwork_id' => $artwork->id,
                            'tag_id'=>$tag->id,
                        ]);
        }
        return redirect()->route('home');
    }



    public function show($id)
    {
        return view('artwork.show', ['artwork' => Artwork::find($id)]);
    }

    public function edit($id)
    {
        $categories=\App\Category::all();
        $artworks=Artwork::findOrFail($id);
        //$artwork_tags=ArtworkTag::where('artwork_id','=',$artwork->id)->get();
        $tags="";
        foreach($artworks->artwork_tags as $artwork_tag){
            //$tags.=$artwork_tag->tag_id;
            $tags.=$artwork_tag->tag->name." ";
        }
        return view('artwork.edit', ['artwork' => $artworks])->with('categories', $categories)->with('tags', $tags);
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title'=>'required|max:30',
            'description'=>'max:2000',
            'category'=>'required'
        ]);
        $artwork = App\Artwork::find($id);
        $artwork->name=$request->title;
        $artwork->description=$request->description;
        $artwork->save();

        
        
        $artwork_tags_prev=App\ArtworkTag::where('artwork_id','=',$artwork->id)->get();
        $artwork_categories_prev=App\ArtworkCategory::where('artwork_id','=',$artwork->id)->get();
	

        /////adds new tags and its relations with artwork
        $words = preg_split('/\s+/', $request->tags, -1, PREG_SPLIT_NO_EMPTY);
                foreach($words as $rawTag){
                $tag = Tag::where('name', $rawTag)->first();
                                if ($tag==null ){//if tag does not exists
                                    $tag=Tag::create([
                                        'name' => $rawTag,
                                        'count'=>1,
                                    ]);
                                    ArtworkTag::create([
                                        'artwork_id' => $artwork->id,
                                        'tag_id'=>$tag->id,
                                    ]);
                                    
                                }
                                else{//if exists
                                    $artwork_has_tag=false;
                                    foreach($artwork_tags_prev as $artwork_tag_prev){//cycles through artworks tags  before update
                                        if($artwork_tag_prev==$tag){
                                            $artwork_has_tag=true;
                                            break;
                                        }
                                    }
                                    if($artwork_has_tag){//if tag already exists and artwork has it
                                        $artwork_tag_prev->delete();
                                    }
                                    else{//if tag already exists and artwork doesnt have it
                                        $tag->count++;
                                        $tag->save();
                                        ArtworkTag::create([
                                            'artwork_id' => $artwork->id,
                                            'tag_id'=>$tag->id,
                                        ]);
                                        
                                    }
                                    
                                }
                               
        }
        return redirect()->route('home');
    }

    public function destroy($id)
    {
        $artwork=Artwork::findOrFail($id);
        $artwork->delete();
        return view('home');
    }
    public function fresh()
    {
        return view('artwork.index', ['artworks' => Artwork::orderBy('upload_date', 'desc')->paginate(12)]);
    }
    public function trends()
    {
        $date= Carbon::now()->toDateString();
        return view('artwork.trends', ['artworks' => Artwork::whereDate('upload_date',$date)->orderBy('like_count', 'desc')->paginate(12)]);
    }
    
}

resources/views/artwork/create.blade.php
@extends('layouts.app')

@section('content')
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css">

<div class="container">
   <div class="row">
       <div class="col-md-10 col-md-offset-1">
           <div class="panel panel-default">
               <div class="panel-heading">Artwork submission</div>

               <div class="panel-body">
               @if (count($errors) > 0)
                   <div class="alert alert-danger">
                   <ul>
                       @foreach ($errors->all() as $error)
                           <li>{{ $error }}</li>
                       @endforeach
                   </ul>
               </div>
               @endif
               <form class="form-horizontal" action="{{ route('artwork.store') }}" method="POST"  enctype="multipart/form-data">
                       {{ csrf_field() }}
                       <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                           <label for="title" class="col-md-4 control-label">Title</label>
                           <div class="col-md-6">
                               <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}" required autofocus>
                               @if ($errors->has('title'))
                                   <span class="help-block">
                                       <strong>{{ $errors->get('title') }}</strong>
                                   </span>
                               @endif
                           </div>
                       </div>
                       <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                           <label for="description" class="col-md-4 control-label">Description</label>
                           <div class="col-md-6">
                               <textarea id="description" type="text" class="form-control" name="description" rows="15"  required autofocus>{{ old('description') }}</textarea>
                               @if ($errors->has('description'))
                                   <span class="help-block">
                                       <strong>{{ $errors->get('description') }}</strong>
                                   </span>
                               @endif
                           </div>
                       </div>
                       <div class="form-group{{ $errors->has('file') ? ' has-error' : '' }}">
                           <label for="artwork" class="col-md-4 control-label">Artwork</label>
                           <div class="col-md-6">
                           <input class="field" id="artwork" name="artwork"  type="file">
                               @if ($errors->has('file'))
                                   <span class="help-block">
                                       <strong>{{ $errors->get('description') }}</strong>
                                   </span>
                               @endif
                           </div>
                       </div>
                       <div class="form-group">
                           <label for="category" class="col-md-4 control-label">Select category:</label>  
                           <div class="col-md-6">


                          
                                  
                                   <select id="category" multiple="multiple" name="category">
                                   @foreach($categories as $category)
                                   <option value="{{$category->id}}"}}  {{ old('category')==$category->id?"selected":"" }}     >{{$category->name}}</option>
                                   @endforeach
                               </select>
                               </div>
                              
                               <script type="text/javascript">
                                   $(document).ready(function() {
                                       $('#category').multiselect();
                                   });
                               </script>


                          
                      
                       </div>
                       <div class="form-group{{ $errors->has('tags') ? ' has-error' : '' }}">
                           <label for="tags" class="col-md-4 control-label">Tags</label>
                           <div class="col-md-6">
                               <input id="tags" type="text" class="form-control" name="tags" value="{{ old('tags') }}" autofocus>
                               @if ($errors->has('tags'))
                                   <span class="help-block">
                                       <strong>{{ $errors->get('name') }}</strong>
                                   </span>
                               @endif
                           </div>
                       </div>
                       <div class="form-group">
                           <div class="col-md-8 col-md-offset-4">
                               <button type="submit" class="btn btn-primary">
                                   Submit
                               </button>
                           </div>
                       </div>
                       </div>
                   </form>
               </div>
           </div>
       </div>
   </div>
</div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css">


@endsection

resources/views/artwork/edit.blade.php
@extends('layouts.app')

@section('content')





<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Artwork edit</div>
                <div class="panel-body">
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <form class="form-horizontal" action="{{ route('artwork.update', $artwork->id) }}" method="PATCH"  >
                        {{ csrf_field() }}
                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="title" class="col-md-4 control-label">Title</label>
                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control" name="title" value="{{ $artwork->name }}" required autofocus>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->get('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Description</label>
                            <div class="col-md-6">
                                <textarea id="description" type="text" class="form-control" name="description" rows="15"  required autofocus>{{ $artwork->description }}</textarea>
                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->get('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="category" class="col-md-4 control-label">Select category:</label>   
                            <div class="col-md-6">     
                                <select id="category" class="form-control" name="category" > 
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}"}}      >{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('tags') ? ' has-error' : '' }}">
                            <label for="tags" class="col-md-4 control-label">Tags</label>
                            <div class="col-md-6">
                                <input id="tags" type="text" class="form-control" name="tags" value="{{ $tags }}" autofocus>
                                @if ($errors->has('tags'))
                                    <span class="help-block">
                                        <strong>{{ $errors->get('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Save
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/artwork/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">All artworks</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    
                <div class="row">
                @foreach($artworks as $a)
                    <div class="col-xs-6 col-md-3">
                        <a href="{{route('artwork.show', ['id' => $a->id])}}" class="thumbnail">
                        <img src="storage/artworks/{{ $a['file_path'] }}" alt="...">
                        </a>
                </div>
                @endforeach
                
                    </div>
                    {{ $artworks->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/artwork/search.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Search results for {{Request::get('searchText')}}</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    
                <div class="row">
                <div class="col"><h4 style="padding-left:15px!important">Search for {{Request::get('searchText')}}: 
                @if (!count($artworks))
                            Absolutely nothing!
                @else
                            {{count($artworks)}}
                @endif
                </h42></div>
                @foreach($artworks as $a)
                    <div class="col-xs-6 col-md-3">
                        <a href="{{route('artwork.show', ['id' => $a->id])}}" class="thumbnail">
                        <img src="storage/artworks/{{ $a['file_path'] }}" alt="...">
                        </a>
                </div>
                @endforeach
                    </div>
                    {{ $artworks->appends(Request::only('searchText'))->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/artwork/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Artwork page!</div>
                <div class="panel-body">
                    <div class="panel panel-primary">
                    <div class="panel-heading">Artwork Name: {{ $artwork->name }}</div>
                    <div class="panel-body">
                    <div class="panel-body">

                 

                        <div class="panel-body">    
                            <a href="{{route('artwork.show', ['id' => $artwork->id])}}">
                                <img class="img-responsive" src="{{URL::to('/')}}/storage/artworks/{{ $artwork->file_path }}" alt="{{ $artwork->name }}">
                            </a>

                    </div>
                
                                            
                    <table class="table table-bordered table-responsive">

                    
                        <tbody>
                        

                            <tr>
                                <td>description</td>
                                <td>
                                @if(empty($artwork->description))
                                    No description.
                                @else
                                    {{ $artwork->description }}
                                @endif
                                </td>
                            </tr>
                            <tr>
                                <td>upload date</td>
                                <td>{{ $artwork->upload_date }}</td>
                            </tr>
                            <tr>
                                <td>likes</td>
                                <td>{{ $artwork->like_count }}</td>
                            </tr>
                            <tr>
                                <td>views</td>
                                <td>{{ $artwork->view_count }}</td>
                            </tr>
                            <tr>
                                <td>file path</td>
                                <td>{{ $artwork->file_path }}</td>
                            </tr>
                            <tr>
                                <td>Uploader</td>
                                <td>{{ $artwork->user->name }}</td>
                            </tr>
                        </tbody>
                    </table>
                    </div>
                    <div class="panel-footer">
                        @auth
                         <a href="" style="color:#13afea!important">Leave a like</a>
                        @else
                            <a href="{{route('login')}}" style="color:#13afea!important">Log in</a> or <a href="{{route('register')}}" style="color:#13afea!important">Register</a> to leave a comment
                        @endauth
                    </div>
                    </div>
                    <p><h2>Categories:</h2></p>
                    @if(!$artwork->artwork_categories->isEmpty())
                        @foreach($artwork->artwork_categories as $category)
                        <a href="#" class="badge badge-primary">{{ $category->category->name }}</a>
                        @endforeach
                    @else
                        Owww! No categories!
                    @endif
                    <p><h2>Tags:</h2></p>
                    @if(!$artwork->artwork_tags->isEmpty())
                        @foreach($artwork->artwork_tags as $tags)
                        <a href="#" class="badge badge-primary">{{ $tags->tag->name }}</a>
                        @endforeach
                    @else
                        Owww! No tags!
                    @endif
                    
                    


                    {{ $с['text'] }}, {{ $с['date'] }}, {{ $с['like_count'] }}</br>

                    @endforeach
                    <textarea id="comment" type="text" class="form-control" name="description" rows="15"  required autofocus> </textarea>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/artwork/trends.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Trendy artworks</div>
                
                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    @foreach($artworks as $artwork)
                    <div class="panel-body">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-6">
                            {{ $artwork->upload_date }},
                            {{ $artwork->name }}
                            </div>
                            <div class="col-md-6 text-right">
                            <a href="{{route('user.show', ['id' => $artwork->user_id])}}">
                            {{ $artwork->user->name }}
                            </a>
                            </div>
                        </div>
                        </div>
                        <div class="panel-body">    
                            <h2>{{ $artwork->name }}</h2>
                            <a href="{{route('artwork.show', ['id' => $artwork->id])}}">
                                <img class="img-responsive" src="storage/artworks/{{ $artwork->file_path }}" alt="{{ $artwork->name }}" style="padding-top:30px!important; padding-bottom:30px!important">
                            </a >
                            {{ str_limit($artwork->description, 200) }}
                            <p><a href="{{route('artwork.show', ['id' => $artwork->id])}}" style="color:#13afea!important">Read more</a></p>
                        </div>
                        <div class="panel-footer">
                                @foreach($artwork->artwork_categories as $category)
                                <a href="#" class="badge badge-primary">{{ $category->category->name }}</a>
                                @endforeach
                                @foreach($artwork->artwork_tags as $tags)
                                <a href="#" class="badge badge-success">{{ $tags->tag->name }}</a>
                                @endforeach
                        </div>
                    </div>
                    </div>
                    @endforeach
                </div>
                <div class="panel-footer">
                {{ $artworks->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection