routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::resource('artwork', 'ArtworkController');
Route::resource('user', 'UserController');

Route::get('fresh', 'ArtworkController@fresh')->name('artwork.fresh');
Route::get('trends', 'ArtworkController@trends')->name('artwork.trends');

Route::get('home', 'HomeController@index')->name('home');
Route::get('search', 'SearchController@search')->name('artwork.search');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Home dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    <p>You are logged in!</p>
                    <p><a class="btn btn-primary" href="{{route('artwork.create')}}" role="button">Submit artwork</a></p>
                            <div class="panel panel-default">
                        <div class="panel-heading">Your recent artworks</div>

                        <div class="panel-body">
                            @if (session('status'))
                                <div class="alert alert-success">
                                    {{ session('status') }}
                                </div>
                            @endif
                            
                            
                        <div class="row">

                        @unless (count($artworks))
                            <div class="col"><h3 style="text-align:center!important;">You have no artworks yet!</h3></div>
                        @endunless
                            @foreach($artworks as $a)
                                <div class="col-xs-6 col-md-3">
                                    <a href="{{route('artwork.show', ['id' => $a->id])}}" class="thumbnail">
                                    <img src="storage/artworks/{{ $a['file_path'] }}" alt="...">
                                    </a>
                                    <a href="{{route('artwork.edit', ['id' => $a->id])}}">edit</a>
                            </div>
                            @endforeach
                            </div>
                            {{ $artworks->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection