routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::resource('artwork', 'ArtworkController');
Route::resource('user', 'UserController');

Route::get('fresh', 'ArtworkController@fresh')->name('artwork.fresh');
Route::get('trends', 'ArtworkController@trends')->name('artwork.trends');

Route::get('home', 'HomeController@index')->name('home');
Route::get('search', 'SearchController@search')->name('artwork.search');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
 
    <title>{{ config('app.name', 'WebGallery') }}</title>
    <link href="{{asset('css/style.css')}}" rel="stylesheet">
 
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">    
            <div class="container">
                <div class="navbar-header">
                <a class="navbar-brand" href="/"><img src="{{URL::to('/')}}/picture_ref/Icon5.png" width="130px" length="130px" style="padding-right:-15px;"> </a> 
                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
 
                    <!-- Branding Image -->
                    <!-- <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a> -->
                </div>
 
                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        <!--Не удалять! -->
                        <!-- <li class="{{ Route::currentRouteNamed('login') ? 'active' : '' }}"><a href="{{ route('login') }}">Login</a></li>-->

                        <li class=""><a class="ex" href="{{ route('artwork.trends') }}">Trends</a></li>
                        <li class=""><a class="ex" href="{{ route('artwork.fresh') }}">Fresh</a></li>
                        <li class=""><a class="ex" href="{{ route('artwork.index') }}">Artworks</a></li>
                    </ul>
 
                    <!-- Right Side Of Navbar -->
                    <form class="navbar-form navbar-left" method="GET" action="{{route('artwork.search')}}">
                    <div class="form-group">
                    <input type="text" class="form-control" name="searchText" id="searchTest" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
 
 
                        @guest
                       
                        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css">
 
                            <li><a class="ex" href="{{ route('login') }}"style="color: #f74d4d">Login</a></li>
                            <li><a class="ex" href="{{ route('register') }}"style="color: #f74d4d">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
 
                                <ul class="dropdown-menu">
                                    <li>
                                    <a href="{{route('user.edit', ['id' => Auth::user()->id]) }}" >
                                            Edit account
                                        </a>
                                        <a href="{{ url('home') }}">Home</a>

                                        @if(Auth::user()->isAdmin())
                                        <a href="{{route('user.index')}}">
                                            Admin panel
                                        </a>
                                        @endif
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>
 
                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
 
        @yield('content')

    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css">
</body>
@include('layouts.footer')
</html> 

resources/views/layouts/artworks.blade.php
<div class="panel-body">
@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif


<div class="row">
@foreach($artworks as $a)
<div class="col-xs-6 col-md-3">
    <a href="{{route('artwork.show', ['id' => $a->id])}}" class="thumbnail">
    <img src="storage/artworks/{{ $a['file_path'] }}" alt="...">
    </a>
</div>
@endforeach

</div>
{{ $artworks->links() }}
</div>

resources/views/layouts/footer.blade.php
<link href="{{asset('css/style.css')}}" rel="stylesheet">
<div class="footer">

   <div> © All rights reserved <?php echo date("Y"); ?></div>
</div>